version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            pip install Flask pymongo
      - run:
          name: Run Unit Tests
          command: python tests.py
      - store_test_results: 
          path: test-results
      - store_artifacts: 
          path: test-results
